id = "amber"
name = "Amber"
description = "Amber Language support."
version = "0.1.0"
schema_version = 1
authors = ["Paweł Karaś <pkaras.it@gmail.com>"]
repository = "https://github.com/Ph0enixKM/zed-amber-extension"

[grammars.amber]
repository = "https://github.com/amber-lang/tree-sitter-amber"
commit = "0d553f126317f8d937647d062189fb1e439097ea"
