id = "amber"
name = "Amber"
description = "Amber Language support."
version = "0.1.0"
schema_version = 1
authors = ["Paweł Karaś <pkaras.it@gmail.com>"]
repository = "https://github.com/Ph0enixKM/zed-amber-extension"

[grammars.amber]
repository = "https://github.com/amber-lang/tree-sitter-amber"
commit = "a3ac6e96edf821ce1a1358e4ecf13ed27e6e30be"
